# Server Port
server.port=8080

# PostgreSQL Veritaban? Ba?lant?s?
spring.datasource.url=jdbc:postgresql://localhost:5432/Defect Reverse-Tracker
spring.datasource.username=postgres
spring.datasource.password=filCeyda10?


spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# true: her başlatmada demo veriyi sıfırla ve yeniden yükle (üretimde false yapın)
app.seed.reset=false
